# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "MyDancerApp"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'
     STRICT: 1
     COMPILE_DIR: 'caches/templates'
     COMPILE_EXT: '.ttc'

plugins:
    Database:
        driver: 'mysql'
        database: 'kwasr'
        host: 'localhost'
        port: 3306
        username: 'kwasr_user'
        password: 'ntx3qn1sgLuA'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'", "SET SQL_MODE='TRADITIONAL'" ]
        log_queries: 1
#        handle_class: 'My::Super::Sexy::Database::Handle'

################ App settings ##################
supported_languages: ["en","nl"]
